# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from contracts.common import common_pb2 as common_dot_common__pb2
from contracts import gateway_pb2 as gateway__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in gateway_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GatewayServiceStub(object):
    """Gateway Service - Orchestrates workflows and provides API gateway
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSystemStatus = channel.unary_unary(
                '/arduino_trader.gateway.GatewayService/GetSystemStatus',
                request_serializer=gateway__pb2.GetSystemStatusRequest.SerializeToString,
                response_deserializer=gateway__pb2.GetSystemStatusResponse.FromString,
                _registered_method=True)
        self.TriggerTradingCycle = channel.unary_stream(
                '/arduino_trader.gateway.GatewayService/TriggerTradingCycle',
                request_serializer=gateway__pb2.TriggerTradingCycleRequest.SerializeToString,
                response_deserializer=gateway__pb2.TradingCycleUpdate.FromString,
                _registered_method=True)
        self.ProcessDeposit = channel.unary_unary(
                '/arduino_trader.gateway.GatewayService/ProcessDeposit',
                request_serializer=gateway__pb2.ProcessDepositRequest.SerializeToString,
                response_deserializer=gateway__pb2.ProcessDepositResponse.FromString,
                _registered_method=True)
        self.GetJobStatus = channel.unary_unary(
                '/arduino_trader.gateway.GatewayService/GetJobStatus',
                request_serializer=gateway__pb2.GetJobStatusRequest.SerializeToString,
                response_deserializer=gateway__pb2.GetJobStatusResponse.FromString,
                _registered_method=True)
        self.ListJobs = channel.unary_unary(
                '/arduino_trader.gateway.GatewayService/ListJobs',
                request_serializer=gateway__pb2.ListJobsRequest.SerializeToString,
                response_deserializer=gateway__pb2.ListJobsResponse.FromString,
                _registered_method=True)
        self.TriggerJob = channel.unary_unary(
                '/arduino_trader.gateway.GatewayService/TriggerJob',
                request_serializer=gateway__pb2.TriggerJobRequest.SerializeToString,
                response_deserializer=gateway__pb2.TriggerJobResponse.FromString,
                _registered_method=True)
        self.GetServicesHealth = channel.unary_unary(
                '/arduino_trader.gateway.GatewayService/GetServicesHealth',
                request_serializer=gateway__pb2.GetServicesHealthRequest.SerializeToString,
                response_deserializer=gateway__pb2.GetServicesHealthResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/arduino_trader.gateway.GatewayService/HealthCheck',
                request_serializer=common_dot_common__pb2.Empty.SerializeToString,
                response_deserializer=common_dot_common__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class GatewayServiceServicer(object):
    """Gateway Service - Orchestrates workflows and provides API gateway
    """

    def GetSystemStatus(self, request, context):
        """Get system status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerTradingCycle(self, request, context):
        """Trigger full trading cycle
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessDeposit(self, request, context):
        """Trigger deposit processing
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJobStatus(self, request, context):
        """Get job status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListJobs(self, request, context):
        """List all jobs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerJob(self, request, context):
        """Trigger specific job
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServicesHealth(self, request, context):
        """Get service health
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GatewayServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSystemStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSystemStatus,
                    request_deserializer=gateway__pb2.GetSystemStatusRequest.FromString,
                    response_serializer=gateway__pb2.GetSystemStatusResponse.SerializeToString,
            ),
            'TriggerTradingCycle': grpc.unary_stream_rpc_method_handler(
                    servicer.TriggerTradingCycle,
                    request_deserializer=gateway__pb2.TriggerTradingCycleRequest.FromString,
                    response_serializer=gateway__pb2.TradingCycleUpdate.SerializeToString,
            ),
            'ProcessDeposit': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessDeposit,
                    request_deserializer=gateway__pb2.ProcessDepositRequest.FromString,
                    response_serializer=gateway__pb2.ProcessDepositResponse.SerializeToString,
            ),
            'GetJobStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJobStatus,
                    request_deserializer=gateway__pb2.GetJobStatusRequest.FromString,
                    response_serializer=gateway__pb2.GetJobStatusResponse.SerializeToString,
            ),
            'ListJobs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListJobs,
                    request_deserializer=gateway__pb2.ListJobsRequest.FromString,
                    response_serializer=gateway__pb2.ListJobsResponse.SerializeToString,
            ),
            'TriggerJob': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerJob,
                    request_deserializer=gateway__pb2.TriggerJobRequest.FromString,
                    response_serializer=gateway__pb2.TriggerJobResponse.SerializeToString,
            ),
            'GetServicesHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServicesHealth,
                    request_deserializer=gateway__pb2.GetServicesHealthRequest.FromString,
                    response_serializer=gateway__pb2.GetServicesHealthResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=common_dot_common__pb2.Empty.FromString,
                    response_serializer=common_dot_common__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'arduino_trader.gateway.GatewayService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('arduino_trader.gateway.GatewayService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GatewayService(object):
    """Gateway Service - Orchestrates workflows and provides API gateway
    """

    @staticmethod
    def GetSystemStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arduino_trader.gateway.GatewayService/GetSystemStatus',
            gateway__pb2.GetSystemStatusRequest.SerializeToString,
            gateway__pb2.GetSystemStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerTradingCycle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/arduino_trader.gateway.GatewayService/TriggerTradingCycle',
            gateway__pb2.TriggerTradingCycleRequest.SerializeToString,
            gateway__pb2.TradingCycleUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessDeposit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arduino_trader.gateway.GatewayService/ProcessDeposit',
            gateway__pb2.ProcessDepositRequest.SerializeToString,
            gateway__pb2.ProcessDepositResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJobStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arduino_trader.gateway.GatewayService/GetJobStatus',
            gateway__pb2.GetJobStatusRequest.SerializeToString,
            gateway__pb2.GetJobStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListJobs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arduino_trader.gateway.GatewayService/ListJobs',
            gateway__pb2.ListJobsRequest.SerializeToString,
            gateway__pb2.ListJobsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arduino_trader.gateway.GatewayService/TriggerJob',
            gateway__pb2.TriggerJobRequest.SerializeToString,
            gateway__pb2.TriggerJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetServicesHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arduino_trader.gateway.GatewayService/GetServicesHealth',
            gateway__pb2.GetServicesHealthRequest.SerializeToString,
            gateway__pb2.GetServicesHealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arduino_trader.gateway.GatewayService/HealthCheck',
            common_dot_common__pb2.Empty.SerializeToString,
            common_dot_common__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
