# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from contracts.common import common_pb2 as common_dot_common__pb2
from contracts import optimization_pb2 as optimization__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in optimization_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OptimizationServiceStub(object):
    """Optimization Service - Handles portfolio optimization
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OptimizeAllocation = channel.unary_unary(
                '/arduino_trader.optimization.OptimizationService/OptimizeAllocation',
                request_serializer=optimization__pb2.OptimizeAllocationRequest.SerializeToString,
                response_deserializer=optimization__pb2.OptimizeAllocationResponse.FromString,
                _registered_method=True)
        self.OptimizeExecution = channel.unary_unary(
                '/arduino_trader.optimization.OptimizationService/OptimizeExecution',
                request_serializer=optimization__pb2.OptimizeExecutionRequest.SerializeToString,
                response_deserializer=optimization__pb2.OptimizeExecutionResponse.FromString,
                _registered_method=True)
        self.CalculateRebalancing = channel.unary_unary(
                '/arduino_trader.optimization.OptimizationService/CalculateRebalancing',
                request_serializer=optimization__pb2.CalculateRebalancingRequest.SerializeToString,
                response_deserializer=optimization__pb2.CalculateRebalancingResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/arduino_trader.optimization.OptimizationService/HealthCheck',
                request_serializer=common_dot_common__pb2.Empty.SerializeToString,
                response_deserializer=common_dot_common__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class OptimizationServiceServicer(object):
    """Optimization Service - Handles portfolio optimization
    """

    def OptimizeAllocation(self, request, context):
        """Optimize portfolio allocation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OptimizeExecution(self, request, context):
        """Optimize trade execution
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalculateRebalancing(self, request, context):
        """Calculate optimal rebalancing
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OptimizationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OptimizeAllocation': grpc.unary_unary_rpc_method_handler(
                    servicer.OptimizeAllocation,
                    request_deserializer=optimization__pb2.OptimizeAllocationRequest.FromString,
                    response_serializer=optimization__pb2.OptimizeAllocationResponse.SerializeToString,
            ),
            'OptimizeExecution': grpc.unary_unary_rpc_method_handler(
                    servicer.OptimizeExecution,
                    request_deserializer=optimization__pb2.OptimizeExecutionRequest.FromString,
                    response_serializer=optimization__pb2.OptimizeExecutionResponse.SerializeToString,
            ),
            'CalculateRebalancing': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateRebalancing,
                    request_deserializer=optimization__pb2.CalculateRebalancingRequest.FromString,
                    response_serializer=optimization__pb2.CalculateRebalancingResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=common_dot_common__pb2.Empty.FromString,
                    response_serializer=common_dot_common__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'arduino_trader.optimization.OptimizationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('arduino_trader.optimization.OptimizationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OptimizationService(object):
    """Optimization Service - Handles portfolio optimization
    """

    @staticmethod
    def OptimizeAllocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arduino_trader.optimization.OptimizationService/OptimizeAllocation',
            optimization__pb2.OptimizeAllocationRequest.SerializeToString,
            optimization__pb2.OptimizeAllocationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OptimizeExecution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arduino_trader.optimization.OptimizationService/OptimizeExecution',
            optimization__pb2.OptimizeExecutionRequest.SerializeToString,
            optimization__pb2.OptimizeExecutionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CalculateRebalancing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arduino_trader.optimization.OptimizationService/CalculateRebalancing',
            optimization__pb2.CalculateRebalancingRequest.SerializeToString,
            optimization__pb2.CalculateRebalancingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arduino_trader.optimization.OptimizationService/HealthCheck',
            common_dot_common__pb2.Empty.SerializeToString,
            common_dot_common__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
