# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from contracts.common import common_pb2 as common_dot_common__pb2
from contracts import planning_pb2 as planning__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in planning_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PlanningServiceStub(object):
    """Planning Service - Handles portfolio planning
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatePlan = channel.unary_stream(
                '/arduino_trader.planning.PlanningService/CreatePlan',
                request_serializer=planning__pb2.CreatePlanRequest.SerializeToString,
                response_deserializer=planning__pb2.PlanUpdate.FromString,
                _registered_method=True)
        self.GetPlan = channel.unary_unary(
                '/arduino_trader.planning.PlanningService/GetPlan',
                request_serializer=planning__pb2.GetPlanRequest.SerializeToString,
                response_deserializer=planning__pb2.GetPlanResponse.FromString,
                _registered_method=True)
        self.ListPlans = channel.unary_unary(
                '/arduino_trader.planning.PlanningService/ListPlans',
                request_serializer=planning__pb2.ListPlansRequest.SerializeToString,
                response_deserializer=planning__pb2.ListPlansResponse.FromString,
                _registered_method=True)
        self.GetBestResult = channel.unary_unary(
                '/arduino_trader.planning.PlanningService/GetBestResult',
                request_serializer=planning__pb2.GetBestResultRequest.SerializeToString,
                response_deserializer=planning__pb2.GetBestResultResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/arduino_trader.planning.PlanningService/HealthCheck',
                request_serializer=common_dot_common__pb2.Empty.SerializeToString,
                response_deserializer=common_dot_common__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class PlanningServiceServicer(object):
    """Planning Service - Handles portfolio planning
    """

    def CreatePlan(self, request, context):
        """Create a new portfolio plan (streaming for progress updates)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlan(self, request, context):
        """Get an existing plan
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPlans(self, request, context):
        """List all plans for a portfolio
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBestResult(self, request, context):
        """Get best result for a portfolio
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlanningServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreatePlan': grpc.unary_stream_rpc_method_handler(
                    servicer.CreatePlan,
                    request_deserializer=planning__pb2.CreatePlanRequest.FromString,
                    response_serializer=planning__pb2.PlanUpdate.SerializeToString,
            ),
            'GetPlan': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlan,
                    request_deserializer=planning__pb2.GetPlanRequest.FromString,
                    response_serializer=planning__pb2.GetPlanResponse.SerializeToString,
            ),
            'ListPlans': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPlans,
                    request_deserializer=planning__pb2.ListPlansRequest.FromString,
                    response_serializer=planning__pb2.ListPlansResponse.SerializeToString,
            ),
            'GetBestResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBestResult,
                    request_deserializer=planning__pb2.GetBestResultRequest.FromString,
                    response_serializer=planning__pb2.GetBestResultResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=common_dot_common__pb2.Empty.FromString,
                    response_serializer=common_dot_common__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'arduino_trader.planning.PlanningService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('arduino_trader.planning.PlanningService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PlanningService(object):
    """Planning Service - Handles portfolio planning
    """

    @staticmethod
    def CreatePlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/arduino_trader.planning.PlanningService/CreatePlan',
            planning__pb2.CreatePlanRequest.SerializeToString,
            planning__pb2.PlanUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arduino_trader.planning.PlanningService/GetPlan',
            planning__pb2.GetPlanRequest.SerializeToString,
            planning__pb2.GetPlanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPlans(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arduino_trader.planning.PlanningService/ListPlans',
            planning__pb2.ListPlansRequest.SerializeToString,
            planning__pb2.ListPlansResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBestResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arduino_trader.planning.PlanningService/GetBestResult',
            planning__pb2.GetBestResultRequest.SerializeToString,
            planning__pb2.GetBestResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arduino_trader.planning.PlanningService/HealthCheck',
            common_dot_common__pb2.Empty.SerializeToString,
            common_dot_common__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
