# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from contracts.common import common_pb2 as common_dot_common__pb2
from contracts import portfolio_pb2 as portfolio__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in portfolio_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PortfolioServiceStub(object):
    """Portfolio Service - Handles portfolio state and positions
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPositions = channel.unary_unary(
                '/arduino_trader.portfolio.PortfolioService/GetPositions',
                request_serializer=portfolio__pb2.GetPositionsRequest.SerializeToString,
                response_deserializer=portfolio__pb2.GetPositionsResponse.FromString,
                _registered_method=True)
        self.GetPosition = channel.unary_unary(
                '/arduino_trader.portfolio.PortfolioService/GetPosition',
                request_serializer=portfolio__pb2.GetPositionRequest.SerializeToString,
                response_deserializer=portfolio__pb2.GetPositionResponse.FromString,
                _registered_method=True)
        self.GetSummary = channel.unary_unary(
                '/arduino_trader.portfolio.PortfolioService/GetSummary',
                request_serializer=portfolio__pb2.GetSummaryRequest.SerializeToString,
                response_deserializer=portfolio__pb2.GetSummaryResponse.FromString,
                _registered_method=True)
        self.GetPerformance = channel.unary_unary(
                '/arduino_trader.portfolio.PortfolioService/GetPerformance',
                request_serializer=portfolio__pb2.GetPerformanceRequest.SerializeToString,
                response_deserializer=portfolio__pb2.GetPerformanceResponse.FromString,
                _registered_method=True)
        self.UpdatePositions = channel.unary_unary(
                '/arduino_trader.portfolio.PortfolioService/UpdatePositions',
                request_serializer=portfolio__pb2.UpdatePositionsRequest.SerializeToString,
                response_deserializer=portfolio__pb2.UpdatePositionsResponse.FromString,
                _registered_method=True)
        self.GetCashBalance = channel.unary_unary(
                '/arduino_trader.portfolio.PortfolioService/GetCashBalance',
                request_serializer=portfolio__pb2.GetCashBalanceRequest.SerializeToString,
                response_deserializer=portfolio__pb2.GetCashBalanceResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/arduino_trader.portfolio.PortfolioService/HealthCheck',
                request_serializer=common_dot_common__pb2.Empty.SerializeToString,
                response_deserializer=common_dot_common__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class PortfolioServiceServicer(object):
    """Portfolio Service - Handles portfolio state and positions
    """

    def GetPositions(self, request, context):
        """Get current portfolio positions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPosition(self, request, context):
        """Get a specific position
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSummary(self, request, context):
        """Get portfolio summary
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPerformance(self, request, context):
        """Get portfolio performance
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePositions(self, request, context):
        """Update positions (sync from broker)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCashBalance(self, request, context):
        """Get cash balance
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PortfolioServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPositions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPositions,
                    request_deserializer=portfolio__pb2.GetPositionsRequest.FromString,
                    response_serializer=portfolio__pb2.GetPositionsResponse.SerializeToString,
            ),
            'GetPosition': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPosition,
                    request_deserializer=portfolio__pb2.GetPositionRequest.FromString,
                    response_serializer=portfolio__pb2.GetPositionResponse.SerializeToString,
            ),
            'GetSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSummary,
                    request_deserializer=portfolio__pb2.GetSummaryRequest.FromString,
                    response_serializer=portfolio__pb2.GetSummaryResponse.SerializeToString,
            ),
            'GetPerformance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPerformance,
                    request_deserializer=portfolio__pb2.GetPerformanceRequest.FromString,
                    response_serializer=portfolio__pb2.GetPerformanceResponse.SerializeToString,
            ),
            'UpdatePositions': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePositions,
                    request_deserializer=portfolio__pb2.UpdatePositionsRequest.FromString,
                    response_serializer=portfolio__pb2.UpdatePositionsResponse.SerializeToString,
            ),
            'GetCashBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCashBalance,
                    request_deserializer=portfolio__pb2.GetCashBalanceRequest.FromString,
                    response_serializer=portfolio__pb2.GetCashBalanceResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=common_dot_common__pb2.Empty.FromString,
                    response_serializer=common_dot_common__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'arduino_trader.portfolio.PortfolioService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('arduino_trader.portfolio.PortfolioService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PortfolioService(object):
    """Portfolio Service - Handles portfolio state and positions
    """

    @staticmethod
    def GetPositions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arduino_trader.portfolio.PortfolioService/GetPositions',
            portfolio__pb2.GetPositionsRequest.SerializeToString,
            portfolio__pb2.GetPositionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arduino_trader.portfolio.PortfolioService/GetPosition',
            portfolio__pb2.GetPositionRequest.SerializeToString,
            portfolio__pb2.GetPositionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arduino_trader.portfolio.PortfolioService/GetSummary',
            portfolio__pb2.GetSummaryRequest.SerializeToString,
            portfolio__pb2.GetSummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPerformance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arduino_trader.portfolio.PortfolioService/GetPerformance',
            portfolio__pb2.GetPerformanceRequest.SerializeToString,
            portfolio__pb2.GetPerformanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePositions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arduino_trader.portfolio.PortfolioService/UpdatePositions',
            portfolio__pb2.UpdatePositionsRequest.SerializeToString,
            portfolio__pb2.UpdatePositionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCashBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arduino_trader.portfolio.PortfolioService/GetCashBalance',
            portfolio__pb2.GetCashBalanceRequest.SerializeToString,
            portfolio__pb2.GetCashBalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arduino_trader.portfolio.PortfolioService/HealthCheck',
            common_dot_common__pb2.Empty.SerializeToString,
            common_dot_common__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
