# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from contracts.common import common_pb2 as common_dot_common__pb2
from contracts import scoring_pb2 as scoring__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in scoring_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ScoringServiceStub(object):
    """Scoring Service - Handles security scoring
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ScoreSecurity = channel.unary_unary(
                '/arduino_trader.scoring.ScoringService/ScoreSecurity',
                request_serializer=scoring__pb2.ScoreSecurityRequest.SerializeToString,
                response_deserializer=scoring__pb2.ScoreSecurityResponse.FromString,
                _registered_method=True)
        self.BatchScoreSecurities = channel.unary_unary(
                '/arduino_trader.scoring.ScoringService/BatchScoreSecurities',
                request_serializer=scoring__pb2.BatchScoreSecuritiesRequest.SerializeToString,
                response_deserializer=scoring__pb2.BatchScoreSecuritiesResponse.FromString,
                _registered_method=True)
        self.ScorePortfolio = channel.unary_unary(
                '/arduino_trader.scoring.ScoringService/ScorePortfolio',
                request_serializer=scoring__pb2.ScorePortfolioRequest.SerializeToString,
                response_deserializer=scoring__pb2.ScorePortfolioResponse.FromString,
                _registered_method=True)
        self.GetScoreHistory = channel.unary_unary(
                '/arduino_trader.scoring.ScoringService/GetScoreHistory',
                request_serializer=scoring__pb2.GetScoreHistoryRequest.SerializeToString,
                response_deserializer=scoring__pb2.GetScoreHistoryResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/arduino_trader.scoring.ScoringService/HealthCheck',
                request_serializer=common_dot_common__pb2.Empty.SerializeToString,
                response_deserializer=common_dot_common__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class ScoringServiceServicer(object):
    """Scoring Service - Handles security scoring
    """

    def ScoreSecurity(self, request, context):
        """Score a single security
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchScoreSecurities(self, request, context):
        """Score multiple securities (batch)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScorePortfolio(self, request, context):
        """Score entire portfolio
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScoreHistory(self, request, context):
        """Get historical scores for a security
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScoringServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ScoreSecurity': grpc.unary_unary_rpc_method_handler(
                    servicer.ScoreSecurity,
                    request_deserializer=scoring__pb2.ScoreSecurityRequest.FromString,
                    response_serializer=scoring__pb2.ScoreSecurityResponse.SerializeToString,
            ),
            'BatchScoreSecurities': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchScoreSecurities,
                    request_deserializer=scoring__pb2.BatchScoreSecuritiesRequest.FromString,
                    response_serializer=scoring__pb2.BatchScoreSecuritiesResponse.SerializeToString,
            ),
            'ScorePortfolio': grpc.unary_unary_rpc_method_handler(
                    servicer.ScorePortfolio,
                    request_deserializer=scoring__pb2.ScorePortfolioRequest.FromString,
                    response_serializer=scoring__pb2.ScorePortfolioResponse.SerializeToString,
            ),
            'GetScoreHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScoreHistory,
                    request_deserializer=scoring__pb2.GetScoreHistoryRequest.FromString,
                    response_serializer=scoring__pb2.GetScoreHistoryResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=common_dot_common__pb2.Empty.FromString,
                    response_serializer=common_dot_common__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'arduino_trader.scoring.ScoringService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('arduino_trader.scoring.ScoringService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ScoringService(object):
    """Scoring Service - Handles security scoring
    """

    @staticmethod
    def ScoreSecurity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arduino_trader.scoring.ScoringService/ScoreSecurity',
            scoring__pb2.ScoreSecurityRequest.SerializeToString,
            scoring__pb2.ScoreSecurityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchScoreSecurities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arduino_trader.scoring.ScoringService/BatchScoreSecurities',
            scoring__pb2.BatchScoreSecuritiesRequest.SerializeToString,
            scoring__pb2.BatchScoreSecuritiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScorePortfolio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arduino_trader.scoring.ScoringService/ScorePortfolio',
            scoring__pb2.ScorePortfolioRequest.SerializeToString,
            scoring__pb2.ScorePortfolioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetScoreHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arduino_trader.scoring.ScoringService/GetScoreHistory',
            scoring__pb2.GetScoreHistoryRequest.SerializeToString,
            scoring__pb2.GetScoreHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arduino_trader.scoring.ScoringService/HealthCheck',
            common_dot_common__pb2.Empty.SerializeToString,
            common_dot_common__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
