# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from contracts.common import common_pb2 as common_dot_common__pb2
from contracts import trading_pb2 as trading__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in trading_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TradingServiceStub(object):
    """Trading Service - Handles trade execution
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteTrade = channel.unary_unary(
                '/arduino_trader.trading.TradingService/ExecuteTrade',
                request_serializer=trading__pb2.ExecuteTradeRequest.SerializeToString,
                response_deserializer=trading__pb2.ExecuteTradeResponse.FromString,
                _registered_method=True)
        self.BatchExecuteTrades = channel.unary_unary(
                '/arduino_trader.trading.TradingService/BatchExecuteTrades',
                request_serializer=trading__pb2.BatchExecuteTradesRequest.SerializeToString,
                response_deserializer=trading__pb2.BatchExecuteTradesResponse.FromString,
                _registered_method=True)
        self.GetTradeStatus = channel.unary_unary(
                '/arduino_trader.trading.TradingService/GetTradeStatus',
                request_serializer=trading__pb2.GetTradeStatusRequest.SerializeToString,
                response_deserializer=trading__pb2.GetTradeStatusResponse.FromString,
                _registered_method=True)
        self.GetTradeHistory = channel.unary_unary(
                '/arduino_trader.trading.TradingService/GetTradeHistory',
                request_serializer=trading__pb2.GetTradeHistoryRequest.SerializeToString,
                response_deserializer=trading__pb2.GetTradeHistoryResponse.FromString,
                _registered_method=True)
        self.CancelTrade = channel.unary_unary(
                '/arduino_trader.trading.TradingService/CancelTrade',
                request_serializer=trading__pb2.CancelTradeRequest.SerializeToString,
                response_deserializer=trading__pb2.CancelTradeResponse.FromString,
                _registered_method=True)
        self.ValidateTrade = channel.unary_unary(
                '/arduino_trader.trading.TradingService/ValidateTrade',
                request_serializer=trading__pb2.ValidateTradeRequest.SerializeToString,
                response_deserializer=trading__pb2.ValidateTradeResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/arduino_trader.trading.TradingService/HealthCheck',
                request_serializer=common_dot_common__pb2.Empty.SerializeToString,
                response_deserializer=common_dot_common__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class TradingServiceServicer(object):
    """Trading Service - Handles trade execution
    """

    def ExecuteTrade(self, request, context):
        """Execute a single trade
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchExecuteTrades(self, request, context):
        """Execute multiple trades (batch)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTradeStatus(self, request, context):
        """Get trade status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTradeHistory(self, request, context):
        """Get trade history
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelTrade(self, request, context):
        """Cancel a pending trade
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateTrade(self, request, context):
        """Validate trade (pre-execution check)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TradingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteTrade': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteTrade,
                    request_deserializer=trading__pb2.ExecuteTradeRequest.FromString,
                    response_serializer=trading__pb2.ExecuteTradeResponse.SerializeToString,
            ),
            'BatchExecuteTrades': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchExecuteTrades,
                    request_deserializer=trading__pb2.BatchExecuteTradesRequest.FromString,
                    response_serializer=trading__pb2.BatchExecuteTradesResponse.SerializeToString,
            ),
            'GetTradeStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTradeStatus,
                    request_deserializer=trading__pb2.GetTradeStatusRequest.FromString,
                    response_serializer=trading__pb2.GetTradeStatusResponse.SerializeToString,
            ),
            'GetTradeHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTradeHistory,
                    request_deserializer=trading__pb2.GetTradeHistoryRequest.FromString,
                    response_serializer=trading__pb2.GetTradeHistoryResponse.SerializeToString,
            ),
            'CancelTrade': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelTrade,
                    request_deserializer=trading__pb2.CancelTradeRequest.FromString,
                    response_serializer=trading__pb2.CancelTradeResponse.SerializeToString,
            ),
            'ValidateTrade': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateTrade,
                    request_deserializer=trading__pb2.ValidateTradeRequest.FromString,
                    response_serializer=trading__pb2.ValidateTradeResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=common_dot_common__pb2.Empty.FromString,
                    response_serializer=common_dot_common__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'arduino_trader.trading.TradingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('arduino_trader.trading.TradingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TradingService(object):
    """Trading Service - Handles trade execution
    """

    @staticmethod
    def ExecuteTrade(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arduino_trader.trading.TradingService/ExecuteTrade',
            trading__pb2.ExecuteTradeRequest.SerializeToString,
            trading__pb2.ExecuteTradeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchExecuteTrades(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arduino_trader.trading.TradingService/BatchExecuteTrades',
            trading__pb2.BatchExecuteTradesRequest.SerializeToString,
            trading__pb2.BatchExecuteTradesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTradeStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arduino_trader.trading.TradingService/GetTradeStatus',
            trading__pb2.GetTradeStatusRequest.SerializeToString,
            trading__pb2.GetTradeStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTradeHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arduino_trader.trading.TradingService/GetTradeHistory',
            trading__pb2.GetTradeHistoryRequest.SerializeToString,
            trading__pb2.GetTradeHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelTrade(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arduino_trader.trading.TradingService/CancelTrade',
            trading__pb2.CancelTradeRequest.SerializeToString,
            trading__pb2.CancelTradeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateTrade(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arduino_trader.trading.TradingService/ValidateTrade',
            trading__pb2.ValidateTradeRequest.SerializeToString,
            trading__pb2.ValidateTradeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arduino_trader.trading.TradingService/HealthCheck',
            common_dot_common__pb2.Empty.SerializeToString,
            common_dot_common__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
