# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from contracts.common import common_pb2 as common_dot_common__pb2
from contracts import universe_pb2 as universe__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in universe_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UniverseServiceStub(object):
    """Universe Service - Handles security universe and market data
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUniverse = channel.unary_unary(
                '/arduino_trader.universe.UniverseService/GetUniverse',
                request_serializer=universe__pb2.GetUniverseRequest.SerializeToString,
                response_deserializer=universe__pb2.GetUniverseResponse.FromString,
                _registered_method=True)
        self.GetSecurity = channel.unary_unary(
                '/arduino_trader.universe.UniverseService/GetSecurity',
                request_serializer=universe__pb2.GetSecurityRequest.SerializeToString,
                response_deserializer=universe__pb2.GetSecurityResponse.FromString,
                _registered_method=True)
        self.SearchSecurities = channel.unary_unary(
                '/arduino_trader.universe.UniverseService/SearchSecurities',
                request_serializer=universe__pb2.SearchSecuritiesRequest.SerializeToString,
                response_deserializer=universe__pb2.SearchSecuritiesResponse.FromString,
                _registered_method=True)
        self.SyncPrices = channel.unary_stream(
                '/arduino_trader.universe.UniverseService/SyncPrices',
                request_serializer=universe__pb2.SyncPricesRequest.SerializeToString,
                response_deserializer=universe__pb2.SyncPricesUpdate.FromString,
                _registered_method=True)
        self.SyncFundamentals = channel.unary_stream(
                '/arduino_trader.universe.UniverseService/SyncFundamentals',
                request_serializer=universe__pb2.SyncFundamentalsRequest.SerializeToString,
                response_deserializer=universe__pb2.SyncFundamentalsUpdate.FromString,
                _registered_method=True)
        self.GetMarketData = channel.unary_unary(
                '/arduino_trader.universe.UniverseService/GetMarketData',
                request_serializer=universe__pb2.GetMarketDataRequest.SerializeToString,
                response_deserializer=universe__pb2.GetMarketDataResponse.FromString,
                _registered_method=True)
        self.AddSecurity = channel.unary_unary(
                '/arduino_trader.universe.UniverseService/AddSecurity',
                request_serializer=universe__pb2.AddSecurityRequest.SerializeToString,
                response_deserializer=universe__pb2.AddSecurityResponse.FromString,
                _registered_method=True)
        self.RemoveSecurity = channel.unary_unary(
                '/arduino_trader.universe.UniverseService/RemoveSecurity',
                request_serializer=universe__pb2.RemoveSecurityRequest.SerializeToString,
                response_deserializer=universe__pb2.RemoveSecurityResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/arduino_trader.universe.UniverseService/HealthCheck',
                request_serializer=common_dot_common__pb2.Empty.SerializeToString,
                response_deserializer=common_dot_common__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class UniverseServiceServicer(object):
    """Universe Service - Handles security universe and market data
    """

    def GetUniverse(self, request, context):
        """Get all securities in universe
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSecurity(self, request, context):
        """Get a specific security
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchSecurities(self, request, context):
        """Search securities
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncPrices(self, request, context):
        """Sync prices from external APIs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncFundamentals(self, request, context):
        """Sync fundamentals
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMarketData(self, request, context):
        """Get market data for a security
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddSecurity(self, request, context):
        """Add security to universe
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveSecurity(self, request, context):
        """Remove security from universe
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UniverseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUniverse': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUniverse,
                    request_deserializer=universe__pb2.GetUniverseRequest.FromString,
                    response_serializer=universe__pb2.GetUniverseResponse.SerializeToString,
            ),
            'GetSecurity': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSecurity,
                    request_deserializer=universe__pb2.GetSecurityRequest.FromString,
                    response_serializer=universe__pb2.GetSecurityResponse.SerializeToString,
            ),
            'SearchSecurities': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchSecurities,
                    request_deserializer=universe__pb2.SearchSecuritiesRequest.FromString,
                    response_serializer=universe__pb2.SearchSecuritiesResponse.SerializeToString,
            ),
            'SyncPrices': grpc.unary_stream_rpc_method_handler(
                    servicer.SyncPrices,
                    request_deserializer=universe__pb2.SyncPricesRequest.FromString,
                    response_serializer=universe__pb2.SyncPricesUpdate.SerializeToString,
            ),
            'SyncFundamentals': grpc.unary_stream_rpc_method_handler(
                    servicer.SyncFundamentals,
                    request_deserializer=universe__pb2.SyncFundamentalsRequest.FromString,
                    response_serializer=universe__pb2.SyncFundamentalsUpdate.SerializeToString,
            ),
            'GetMarketData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMarketData,
                    request_deserializer=universe__pb2.GetMarketDataRequest.FromString,
                    response_serializer=universe__pb2.GetMarketDataResponse.SerializeToString,
            ),
            'AddSecurity': grpc.unary_unary_rpc_method_handler(
                    servicer.AddSecurity,
                    request_deserializer=universe__pb2.AddSecurityRequest.FromString,
                    response_serializer=universe__pb2.AddSecurityResponse.SerializeToString,
            ),
            'RemoveSecurity': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveSecurity,
                    request_deserializer=universe__pb2.RemoveSecurityRequest.FromString,
                    response_serializer=universe__pb2.RemoveSecurityResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=common_dot_common__pb2.Empty.FromString,
                    response_serializer=common_dot_common__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'arduino_trader.universe.UniverseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('arduino_trader.universe.UniverseService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UniverseService(object):
    """Universe Service - Handles security universe and market data
    """

    @staticmethod
    def GetUniverse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arduino_trader.universe.UniverseService/GetUniverse',
            universe__pb2.GetUniverseRequest.SerializeToString,
            universe__pb2.GetUniverseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSecurity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arduino_trader.universe.UniverseService/GetSecurity',
            universe__pb2.GetSecurityRequest.SerializeToString,
            universe__pb2.GetSecurityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchSecurities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arduino_trader.universe.UniverseService/SearchSecurities',
            universe__pb2.SearchSecuritiesRequest.SerializeToString,
            universe__pb2.SearchSecuritiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncPrices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/arduino_trader.universe.UniverseService/SyncPrices',
            universe__pb2.SyncPricesRequest.SerializeToString,
            universe__pb2.SyncPricesUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncFundamentals(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/arduino_trader.universe.UniverseService/SyncFundamentals',
            universe__pb2.SyncFundamentalsRequest.SerializeToString,
            universe__pb2.SyncFundamentalsUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMarketData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arduino_trader.universe.UniverseService/GetMarketData',
            universe__pb2.GetMarketDataRequest.SerializeToString,
            universe__pb2.GetMarketDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddSecurity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arduino_trader.universe.UniverseService/AddSecurity',
            universe__pb2.AddSecurityRequest.SerializeToString,
            universe__pb2.AddSecurityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveSecurity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arduino_trader.universe.UniverseService/RemoveSecurity',
            universe__pb2.RemoveSecurityRequest.SerializeToString,
            universe__pb2.RemoveSecurityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arduino_trader.universe.UniverseService/HealthCheck',
            common_dot_common__pb2.Empty.SerializeToString,
            common_dot_common__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
