"""Domain constants for business logic."""

# Position sizing multipliers
MIN_CONVICTION_MULTIPLIER = 0.8
MAX_CONVICTION_MULTIPLIER = 1.2
MIN_PRIORITY_MULTIPLIER = 0.9
MAX_PRIORITY_MULTIPLIER = 1.1
MIN_VOLATILITY_MULTIPLIER = 0.7
MAX_POSITION_SIZE_MULTIPLIER = 1.2

# Diversification penalty weights
POSITION_PENALTY_WEIGHT = 0.4
GEO_PENALTY_WEIGHT = 0.3
INDUSTRY_PENALTY_WEIGHT = 0.3
MAX_DIVERSIFICATION_PENALTY = 0.5
MAX_POSITION_PENALTY = 0.3

# Priority calculation thresholds
HIGH_GEO_NEED_THRESHOLD = 0.6
LOW_GEO_NEED_THRESHOLD = 0.4
HIGH_INDUSTRY_NEED_THRESHOLD = 0.6

# Currency codes
DEFAULT_CURRENCY = "EUR"
SUPPORTED_CURRENCIES = ["EUR", "USD", "GBP", "HKD"]

# Trade sides
TRADE_SIDE_BUY = "BUY"
TRADE_SIDE_SELL = "SELL"

# Geography codes
GEO_EU = "EU"
GEO_ASIA = "ASIA"
GEO_US = "US"

# Allocation types
ALLOCATION_TYPE_GEOGRAPHY = "geography"
ALLOCATION_TYPE_INDUSTRY = "industry"
