-- Migration 025: Remove partial_execution_generator column from planner_settings
--
-- This migration removes the partial_execution_generator column from planner_settings table.
-- Partial Execution Generator was redundant - sequences of different lengths are already
-- generated by patterns and combinatorial generators.

-- Drop the partial_execution_generator column from planner_settings table
ALTER TABLE planner_settings DROP COLUMN IF EXISTS enable_partial_execution_generator;
