# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'common/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63ommon/common.proto\x12\x15\x61rduino_trader.common\"\x07\n\x05\x45mpty\"@\n\x0eStatusResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0c\n\x04\x63ode\x18\x03 \x01(\x05\"+\n\tTimestamp\x12\x0f\n\x07seconds\x18\x01 \x01(\x03\x12\r\n\x05nanos\x18\x02 \x01(\x05\")\n\x05Money\x12\x0e\n\x06\x61mount\x18\x01 \x01(\t\x12\x10\n\x08\x63urrency\x18\x02 \x01(\t\"G\n\x13HealthCheckResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t*H\n\x08\x43urrency\x12\x18\n\x14\x43URRENCY_UNSPECIFIED\x10\x00\x12\x07\n\x03USD\x10\x01\x12\x07\n\x03\x45UR\x10\x02\x12\x07\n\x03GBP\x10\x03\x12\x07\n\x03JPY\x10\x04*:\n\tTradeSide\x12\x1a\n\x16TRADE_SIDE_UNSPECIFIED\x10\x00\x12\x07\n\x03\x42UY\x10\x01\x12\x08\n\x04SELL\x10\x02*a\n\x0bTradeStatus\x12\x1c\n\x18TRADE_STATUS_UNSPECIFIED\x10\x00\x12\x0b\n\x07PENDING\x10\x01\x12\x0c\n\x08\x45XECUTED\x10\x02\x12\n\n\x06\x46\x41ILED\x10\x03\x12\r\n\tCANCELLED\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CURRENCY']._serialized_start=282
  _globals['_CURRENCY']._serialized_end=354
  _globals['_TRADESIDE']._serialized_start=356
  _globals['_TRADESIDE']._serialized_end=414
  _globals['_TRADESTATUS']._serialized_start=416
  _globals['_TRADESTATUS']._serialized_end=513
  _globals['_EMPTY']._serialized_start=46
  _globals['_EMPTY']._serialized_end=53
  _globals['_STATUSRESPONSE']._serialized_start=55
  _globals['_STATUSRESPONSE']._serialized_end=119
  _globals['_TIMESTAMP']._serialized_start=121
  _globals['_TIMESTAMP']._serialized_end=164
  _globals['_MONEY']._serialized_start=166
  _globals['_MONEY']._serialized_end=207
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=209
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=280
# @@protoc_insertion_point(module_scope)
