# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/position.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'common/position.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from contracts.common import common_pb2 as common_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x63ommon/position.proto\x12\x15\x61rduino_trader.common\x1a\x13\x63ommon/common.proto\"\xb6\x03\n\x08Position\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x0c\n\x04isin\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x10\n\x08quantity\x18\x04 \x01(\x01\x12\x33\n\raverage_price\x18\x05 \x01(\x0b\x32\x1c.arduino_trader.common.Money\x12\x33\n\rcurrent_price\x18\x06 \x01(\x0b\x32\x1c.arduino_trader.common.Money\x12\x32\n\x0cmarket_value\x18\x07 \x01(\x0b\x32\x1c.arduino_trader.common.Money\x12\x30\n\ncost_basis\x18\x08 \x01(\x0b\x32\x1c.arduino_trader.common.Money\x12\x34\n\x0eunrealized_pnl\x18\t \x01(\x0b\x32\x1c.arduino_trader.common.Money\x12\x1a\n\x12unrealized_pnl_pct\x18\n \x01(\x01\x12\x12\n\naccount_id\x18\x0b \x01(\t\x12\x36\n\x0clast_updated\x18\x0c \x01(\x0b\x32 .arduino_trader.common.Timestamp\"B\n\x0cPositionList\x12\x32\n\tpositions\x18\x01 \x03(\x0b\x32\x1f.arduino_trader.common.Positionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.position_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POSITION']._serialized_start=70
  _globals['_POSITION']._serialized_end=508
  _globals['_POSITIONLIST']._serialized_start=510
  _globals['_POSITIONLIST']._serialized_end=576
# @@protoc_insertion_point(module_scope)
