# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/security.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'common/security.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from contracts.common import common_pb2 as common_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x63ommon/security.proto\x12\x15\x61rduino_trader.common\x1a\x13\x63ommon/common.proto\"\xaa\x02\n\x08Security\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x0c\n\x04isin\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x10\n\x08\x65xchange\x18\x04 \x01(\t\x12\x10\n\x08\x63urrency\x18\x05 \x01(\t\x12\x15\n\rsecurity_type\x18\x06 \x01(\t\x12\x33\n\rcurrent_price\x18\x07 \x01(\x0b\x32\x1c.arduino_trader.common.Money\x12\x37\n\rprice_updated\x18\x08 \x01(\x0b\x32 .arduino_trader.common.Timestamp\x12\x13\n\x0bis_tradable\x18\t \x01(\x08\x12\x12\n\nmarket_cap\x18\n \x01(\x01\x12\x0e\n\x06sector\x18\x0b \x01(\t\x12\x10\n\x08industry\x18\x0c \x01(\t\"C\n\x0cSecurityList\x12\x33\n\nsecurities\x18\x01 \x03(\x0b\x32\x1f.arduino_trader.common.Securityb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.security_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SECURITY']._serialized_start=70
  _globals['_SECURITY']._serialized_end=368
  _globals['_SECURITYLIST']._serialized_start=370
  _globals['_SECURITYLIST']._serialized_end=437
# @@protoc_insertion_point(module_scope)
